/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardCreateOrganizationRouteImport } from './routes/dashboard/create-organization'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as DashboardwithSidebarRouteRouteImport } from './routes/dashboard/(with-sidebar)/route'
import { Route as DashboardwithSidebarIndexRouteImport } from './routes/dashboard/(with-sidebar)/index'
import { Route as DashboardwithSidebarSettingsRouteImport } from './routes/dashboard/(with-sidebar)/settings'
import { Route as DashboardwithSidebarCheckInsIndexRouteImport } from './routes/dashboard/(with-sidebar)/check-ins/index'
import { Route as DashboardwithSidebarCheckInsNewRouteImport } from './routes/dashboard/(with-sidebar)/check-ins/new'
import { Route as DashboardwithSidebarCheckInsCheckInIdRouteImport } from './routes/dashboard/(with-sidebar)/check-ins/$checkInId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreateOrganizationRoute =
  DashboardCreateOrganizationRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardwithSidebarRouteRoute =
  DashboardwithSidebarRouteRouteImport.update({
    id: '/(with-sidebar)',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardwithSidebarIndexRoute =
  DashboardwithSidebarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardwithSidebarRouteRoute,
  } as any)
const DashboardwithSidebarSettingsRoute =
  DashboardwithSidebarSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardwithSidebarRouteRoute,
  } as any)
const DashboardwithSidebarCheckInsIndexRoute =
  DashboardwithSidebarCheckInsIndexRouteImport.update({
    id: '/check-ins/',
    path: '/check-ins/',
    getParentRoute: () => DashboardwithSidebarRouteRoute,
  } as any)
const DashboardwithSidebarCheckInsNewRoute =
  DashboardwithSidebarCheckInsNewRouteImport.update({
    id: '/check-ins/new',
    path: '/check-ins/new',
    getParentRoute: () => DashboardwithSidebarRouteRoute,
  } as any)
const DashboardwithSidebarCheckInsCheckInIdRoute =
  DashboardwithSidebarCheckInsCheckInIdRouteImport.update({
    id: '/check-ins/$checkInId',
    path: '/check-ins/$checkInId',
    getParentRoute: () => DashboardwithSidebarRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardwithSidebarRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/create-organization': typeof DashboardCreateOrganizationRoute
  '/dashboard/settings': typeof DashboardwithSidebarSettingsRoute
  '/dashboard/': typeof DashboardwithSidebarIndexRoute
  '/dashboard/check-ins/$checkInId': typeof DashboardwithSidebarCheckInsCheckInIdRoute
  '/dashboard/check-ins/new': typeof DashboardwithSidebarCheckInsNewRoute
  '/dashboard/check-ins': typeof DashboardwithSidebarCheckInsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardwithSidebarIndexRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/create-organization': typeof DashboardCreateOrganizationRoute
  '/dashboard/settings': typeof DashboardwithSidebarSettingsRoute
  '/dashboard/check-ins/$checkInId': typeof DashboardwithSidebarCheckInsCheckInIdRoute
  '/dashboard/check-ins/new': typeof DashboardwithSidebarCheckInsNewRoute
  '/dashboard/check-ins': typeof DashboardwithSidebarCheckInsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/(with-sidebar)': typeof DashboardwithSidebarRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/create-organization': typeof DashboardCreateOrganizationRoute
  '/dashboard/(with-sidebar)/settings': typeof DashboardwithSidebarSettingsRoute
  '/dashboard/(with-sidebar)/': typeof DashboardwithSidebarIndexRoute
  '/dashboard/(with-sidebar)/check-ins/$checkInId': typeof DashboardwithSidebarCheckInsCheckInIdRoute
  '/dashboard/(with-sidebar)/check-ins/new': typeof DashboardwithSidebarCheckInsNewRoute
  '/dashboard/(with-sidebar)/check-ins/': typeof DashboardwithSidebarCheckInsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/create-organization'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/check-ins/$checkInId'
    | '/dashboard/check-ins/new'
    | '/dashboard/check-ins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/create-organization'
    | '/dashboard/settings'
    | '/dashboard/check-ins/$checkInId'
    | '/dashboard/check-ins/new'
    | '/dashboard/check-ins'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/(with-sidebar)'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/create-organization'
    | '/dashboard/(with-sidebar)/settings'
    | '/dashboard/(with-sidebar)/'
    | '/dashboard/(with-sidebar)/check-ins/$checkInId'
    | '/dashboard/(with-sidebar)/check-ins/new'
    | '/dashboard/(with-sidebar)/check-ins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/create-organization': {
      id: '/dashboard/create-organization'
      path: '/create-organization'
      fullPath: '/dashboard/create-organization'
      preLoaderRoute: typeof DashboardCreateOrganizationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/(with-sidebar)': {
      id: '/dashboard/(with-sidebar)'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardwithSidebarRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(with-sidebar)/': {
      id: '/dashboard/(with-sidebar)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardwithSidebarIndexRouteImport
      parentRoute: typeof DashboardwithSidebarRouteRoute
    }
    '/dashboard/(with-sidebar)/settings': {
      id: '/dashboard/(with-sidebar)/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardwithSidebarSettingsRouteImport
      parentRoute: typeof DashboardwithSidebarRouteRoute
    }
    '/dashboard/(with-sidebar)/check-ins/': {
      id: '/dashboard/(with-sidebar)/check-ins/'
      path: '/check-ins'
      fullPath: '/dashboard/check-ins'
      preLoaderRoute: typeof DashboardwithSidebarCheckInsIndexRouteImport
      parentRoute: typeof DashboardwithSidebarRouteRoute
    }
    '/dashboard/(with-sidebar)/check-ins/new': {
      id: '/dashboard/(with-sidebar)/check-ins/new'
      path: '/check-ins/new'
      fullPath: '/dashboard/check-ins/new'
      preLoaderRoute: typeof DashboardwithSidebarCheckInsNewRouteImport
      parentRoute: typeof DashboardwithSidebarRouteRoute
    }
    '/dashboard/(with-sidebar)/check-ins/$checkInId': {
      id: '/dashboard/(with-sidebar)/check-ins/$checkInId'
      path: '/check-ins/$checkInId'
      fullPath: '/dashboard/check-ins/$checkInId'
      preLoaderRoute: typeof DashboardwithSidebarCheckInsCheckInIdRouteImport
      parentRoute: typeof DashboardwithSidebarRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardwithSidebarRouteRouteChildren {
  DashboardwithSidebarSettingsRoute: typeof DashboardwithSidebarSettingsRoute
  DashboardwithSidebarIndexRoute: typeof DashboardwithSidebarIndexRoute
  DashboardwithSidebarCheckInsCheckInIdRoute: typeof DashboardwithSidebarCheckInsCheckInIdRoute
  DashboardwithSidebarCheckInsNewRoute: typeof DashboardwithSidebarCheckInsNewRoute
  DashboardwithSidebarCheckInsIndexRoute: typeof DashboardwithSidebarCheckInsIndexRoute
}

const DashboardwithSidebarRouteRouteChildren: DashboardwithSidebarRouteRouteChildren =
  {
    DashboardwithSidebarSettingsRoute: DashboardwithSidebarSettingsRoute,
    DashboardwithSidebarIndexRoute: DashboardwithSidebarIndexRoute,
    DashboardwithSidebarCheckInsCheckInIdRoute:
      DashboardwithSidebarCheckInsCheckInIdRoute,
    DashboardwithSidebarCheckInsNewRoute: DashboardwithSidebarCheckInsNewRoute,
    DashboardwithSidebarCheckInsIndexRoute:
      DashboardwithSidebarCheckInsIndexRoute,
  }

const DashboardwithSidebarRouteRouteWithChildren =
  DashboardwithSidebarRouteRoute._addFileChildren(
    DashboardwithSidebarRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardwithSidebarRouteRoute: typeof DashboardwithSidebarRouteRouteWithChildren
  DashboardCreateOrganizationRoute: typeof DashboardCreateOrganizationRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardwithSidebarRouteRoute: DashboardwithSidebarRouteRouteWithChildren,
  DashboardCreateOrganizationRoute: DashboardCreateOrganizationRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
