/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateOrganizationRouteImport } from './routes/create-organization'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as DashboardwithSidebarRouteRouteImport } from './routes/dashboard/(with-sidebar)/route'
import { Route as DashboardwithSidebarIndexRouteImport } from './routes/dashboard/(with-sidebar)/index'
import { Route as DashboardwithSidebarSettingsRouteImport } from './routes/dashboard/(with-sidebar)/settings'
import { Route as DashboardwithSidebarCheckInsIndexRouteImport } from './routes/dashboard/(with-sidebar)/check-ins/index'
import { Route as DashboardwithSidebarCheckInsNewRouteImport } from './routes/dashboard/(with-sidebar)/check-ins/new'

const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardwithSidebarRouteRoute =
  DashboardwithSidebarRouteRouteImport.update({
    id: '/dashboard/(with-sidebar)',
    path: '/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardwithSidebarIndexRoute =
  DashboardwithSidebarIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardwithSidebarRouteRoute,
  } as any)
const DashboardwithSidebarSettingsRoute =
  DashboardwithSidebarSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardwithSidebarRouteRoute,
  } as any)
const DashboardwithSidebarCheckInsIndexRoute =
  DashboardwithSidebarCheckInsIndexRouteImport.update({
    id: '/check-ins/',
    path: '/check-ins/',
    getParentRoute: () => DashboardwithSidebarRouteRoute,
  } as any)
const DashboardwithSidebarCheckInsNewRoute =
  DashboardwithSidebarCheckInsNewRouteImport.update({
    id: '/check-ins/new',
    path: '/check-ins/new',
    getParentRoute: () => DashboardwithSidebarRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/dashboard': typeof DashboardwithSidebarRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/settings': typeof DashboardwithSidebarSettingsRoute
  '/dashboard/': typeof DashboardwithSidebarIndexRoute
  '/dashboard/check-ins/new': typeof DashboardwithSidebarCheckInsNewRoute
  '/dashboard/check-ins': typeof DashboardwithSidebarCheckInsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/settings': typeof DashboardwithSidebarSettingsRoute
  '/dashboard': typeof DashboardwithSidebarIndexRoute
  '/dashboard/check-ins/new': typeof DashboardwithSidebarCheckInsNewRoute
  '/dashboard/check-ins': typeof DashboardwithSidebarCheckInsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/dashboard/(with-sidebar)': typeof DashboardwithSidebarRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/(with-sidebar)/settings': typeof DashboardwithSidebarSettingsRoute
  '/dashboard/(with-sidebar)/': typeof DashboardwithSidebarIndexRoute
  '/dashboard/(with-sidebar)/check-ins/new': typeof DashboardwithSidebarCheckInsNewRoute
  '/dashboard/(with-sidebar)/check-ins/': typeof DashboardwithSidebarCheckInsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organization'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/check-ins/new'
    | '/dashboard/check-ins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organization'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/check-ins/new'
    | '/dashboard/check-ins'
  id:
    | '__root__'
    | '/'
    | '/create-organization'
    | '/dashboard/(with-sidebar)'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/(with-sidebar)/settings'
    | '/dashboard/(with-sidebar)/'
    | '/dashboard/(with-sidebar)/check-ins/new'
    | '/dashboard/(with-sidebar)/check-ins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateOrganizationRoute: typeof CreateOrganizationRoute
  DashboardwithSidebarRouteRoute: typeof DashboardwithSidebarRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/(with-sidebar)': {
      id: '/dashboard/(with-sidebar)'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardwithSidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/(with-sidebar)/': {
      id: '/dashboard/(with-sidebar)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardwithSidebarIndexRouteImport
      parentRoute: typeof DashboardwithSidebarRouteRoute
    }
    '/dashboard/(with-sidebar)/settings': {
      id: '/dashboard/(with-sidebar)/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardwithSidebarSettingsRouteImport
      parentRoute: typeof DashboardwithSidebarRouteRoute
    }
    '/dashboard/(with-sidebar)/check-ins/': {
      id: '/dashboard/(with-sidebar)/check-ins/'
      path: '/check-ins'
      fullPath: '/dashboard/check-ins'
      preLoaderRoute: typeof DashboardwithSidebarCheckInsIndexRouteImport
      parentRoute: typeof DashboardwithSidebarRouteRoute
    }
    '/dashboard/(with-sidebar)/check-ins/new': {
      id: '/dashboard/(with-sidebar)/check-ins/new'
      path: '/check-ins/new'
      fullPath: '/dashboard/check-ins/new'
      preLoaderRoute: typeof DashboardwithSidebarCheckInsNewRouteImport
      parentRoute: typeof DashboardwithSidebarRouteRoute
    }
  }
}

interface DashboardwithSidebarRouteRouteChildren {
  DashboardwithSidebarSettingsRoute: typeof DashboardwithSidebarSettingsRoute
  DashboardwithSidebarIndexRoute: typeof DashboardwithSidebarIndexRoute
  DashboardwithSidebarCheckInsNewRoute: typeof DashboardwithSidebarCheckInsNewRoute
  DashboardwithSidebarCheckInsIndexRoute: typeof DashboardwithSidebarCheckInsIndexRoute
}

const DashboardwithSidebarRouteRouteChildren: DashboardwithSidebarRouteRouteChildren =
  {
    DashboardwithSidebarSettingsRoute: DashboardwithSidebarSettingsRoute,
    DashboardwithSidebarIndexRoute: DashboardwithSidebarIndexRoute,
    DashboardwithSidebarCheckInsNewRoute: DashboardwithSidebarCheckInsNewRoute,
    DashboardwithSidebarCheckInsIndexRoute:
      DashboardwithSidebarCheckInsIndexRoute,
  }

const DashboardwithSidebarRouteRouteWithChildren =
  DashboardwithSidebarRouteRoute._addFileChildren(
    DashboardwithSidebarRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateOrganizationRoute: CreateOrganizationRoute,
  DashboardwithSidebarRouteRoute: DashboardwithSidebarRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
